// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dns.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetDNSChaosRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pods []*Pod `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	// mode means the chaos mode, values can be "RANDOM" or "ERROR"
	//   "RANDOM": return random IP
	//   "ERROR":  return unknown host error
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// scope means the chaos scope, values can be "INNER", "OUTER" or "ALL":
	//   "INNER": chaos only works on the inner host in Kubernetes cluster
	//   "OUTER": chaos only works on the outer host of Kubernetes cluster
	//   "ALL":   chaos works on all host
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Selector             string   `protobuf:"bytes,5,opt,name=selector,proto3" json:"selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDNSChaosRequest) Reset()         { *m = SetDNSChaosRequest{} }
func (m *SetDNSChaosRequest) String() string { return proto.CompactTextString(m) }
func (*SetDNSChaosRequest) ProtoMessage()    {}
func (*SetDNSChaosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{0}
}

func (m *SetDNSChaosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDNSChaosRequest.Unmarshal(m, b)
}
func (m *SetDNSChaosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDNSChaosRequest.Marshal(b, m, deterministic)
}
func (m *SetDNSChaosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDNSChaosRequest.Merge(m, src)
}
func (m *SetDNSChaosRequest) XXX_Size() int {
	return xxx_messageInfo_SetDNSChaosRequest.Size(m)
}
func (m *SetDNSChaosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDNSChaosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDNSChaosRequest proto.InternalMessageInfo

func (m *SetDNSChaosRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetDNSChaosRequest) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

func (m *SetDNSChaosRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *SetDNSChaosRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *SetDNSChaosRequest) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

type Pod struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{1}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CancelDNSChaosRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelDNSChaosRequest) Reset()         { *m = CancelDNSChaosRequest{} }
func (m *CancelDNSChaosRequest) String() string { return proto.CompactTextString(m) }
func (*CancelDNSChaosRequest) ProtoMessage()    {}
func (*CancelDNSChaosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{2}
}

func (m *CancelDNSChaosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelDNSChaosRequest.Unmarshal(m, b)
}
func (m *CancelDNSChaosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelDNSChaosRequest.Marshal(b, m, deterministic)
}
func (m *CancelDNSChaosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelDNSChaosRequest.Merge(m, src)
}
func (m *CancelDNSChaosRequest) XXX_Size() int {
	return xxx_messageInfo_CancelDNSChaosRequest.Size(m)
}
func (m *CancelDNSChaosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelDNSChaosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelDNSChaosRequest proto.InternalMessageInfo

func (m *CancelDNSChaosRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DNSChaosResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSChaosResponse) Reset()         { *m = DNSChaosResponse{} }
func (m *DNSChaosResponse) String() string { return proto.CompactTextString(m) }
func (*DNSChaosResponse) ProtoMessage()    {}
func (*DNSChaosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{3}
}

func (m *DNSChaosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSChaosResponse.Unmarshal(m, b)
}
func (m *DNSChaosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSChaosResponse.Marshal(b, m, deterministic)
}
func (m *DNSChaosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSChaosResponse.Merge(m, src)
}
func (m *DNSChaosResponse) XXX_Size() int {
	return xxx_messageInfo_DNSChaosResponse.Size(m)
}
func (m *DNSChaosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSChaosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DNSChaosResponse proto.InternalMessageInfo

func (m *DNSChaosResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DNSChaosResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SetDNSChaosRequest)(nil), "pb.SetDNSChaosRequest")
	proto.RegisterType((*Pod)(nil), "pb.Pod")
	proto.RegisterType((*CancelDNSChaosRequest)(nil), "pb.CancelDNSChaosRequest")
	proto.RegisterType((*DNSChaosResponse)(nil), "pb.DNSChaosResponse")
}

func init() { proto.RegisterFile("dns.proto", fileDescriptor_638ff8d8aaf3d8ae) }

var fileDescriptor_638ff8d8aaf3d8ae = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x95, 0x42, 0x6b, 0x99, 0x26, 0xa6, 0x99, 0xd4, 0x06, 0xab, 0x87, 0x86, 0x53, 0x13, 0x13,
	0x0e, 0xf5, 0xe0, 0x45, 0x4f, 0xf4, 0xdc, 0x34, 0xf0, 0x0b, 0x80, 0x9d, 0xe8, 0x01, 0x98, 0x95,
	0xd9, 0xfe, 0x08, 0xe3, 0x9f, 0x36, 0xbb, 0xad, 0xc5, 0xcf, 0xc4, 0xdb, 0xbc, 0xc7, 0x1b, 0xde,
	0x9b, 0xb7, 0x10, 0xaa, 0x56, 0x12, 0xdd, 0xb1, 0x61, 0x1c, 0xe8, 0x32, 0x7e, 0xf3, 0x00, 0x73,
	0x32, 0x9b, 0x6d, 0x9e, 0x3e, 0x17, 0x2c, 0x19, 0xbd, 0xec, 0x49, 0x0c, 0x22, 0x04, 0x6d, 0xd1,
	0x50, 0xe4, 0x2d, 0xbd, 0x55, 0x98, 0xb9, 0x19, 0xaf, 0x21, 0xd0, 0xac, 0x24, 0x1a, 0x2c, 0xfd,
	0xd5, 0x64, 0x7d, 0x9e, 0xe8, 0x32, 0xd9, 0xb1, 0xca, 0x1c, 0x69, 0x17, 0x1a, 0x56, 0x14, 0xf9,
	0x87, 0x05, 0x3b, 0xe3, 0x0c, 0x86, 0x52, 0xb1, 0xa6, 0x28, 0x70, 0xe4, 0x01, 0xe0, 0x02, 0xc6,
	0x42, 0x35, 0x55, 0x86, 0xbb, 0x68, 0xe8, 0x3e, 0x9c, 0x70, 0x7c, 0x0f, 0xfe, 0x8e, 0x15, 0xde,
	0x40, 0x68, 0x1d, 0x45, 0x17, 0xd5, 0x47, 0x84, 0x9e, 0x38, 0x65, 0x1b, 0xf4, 0xd9, 0xe2, 0x5b,
	0xb8, 0x4c, 0x8b, 0xb6, 0xa2, 0xfa, 0x1f, 0x87, 0xc4, 0x0f, 0x30, 0xed, 0x65, 0xa2, 0xb9, 0x15,
	0xc2, 0x39, 0x8c, 0x3a, 0x92, 0x7d, 0x6d, 0x9c, 0x72, 0x9c, 0x1d, 0x11, 0x4e, 0xc1, 0x6f, 0xe4,
	0xe9, 0xe8, 0x65, 0xc7, 0xf5, 0xab, 0x07, 0xfe, 0x66, 0x9b, 0xe3, 0x23, 0x4c, 0x3e, 0x15, 0x87,
	0x73, 0xdb, 0xc7, 0xcf, 0x26, 0x17, 0x33, 0xcb, 0x7f, 0xb7, 0x8b, 0xcf, 0x30, 0x85, 0x8b, 0xaf,
	0x89, 0xf1, 0xca, 0x2a, 0x7f, 0xbd, 0xe2, 0xaf, 0x9f, 0x94, 0x23, 0xf7, 0x90, 0x77, 0xef, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x02, 0x8f, 0xd7, 0x9a, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DNSClient is the client API for DNS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DNSClient interface {
	SetDNSChaos(ctx context.Context, in *SetDNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error)
	CancelDNSChaos(ctx context.Context, in *CancelDNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error)
}

type dNSClient struct {
	cc *grpc.ClientConn
}

func NewDNSClient(cc *grpc.ClientConn) DNSClient {
	return &dNSClient{cc}
}

func (c *dNSClient) SetDNSChaos(ctx context.Context, in *SetDNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error) {
	out := new(DNSChaosResponse)
	err := c.cc.Invoke(ctx, "/pb.DNS/SetDNSChaos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSClient) CancelDNSChaos(ctx context.Context, in *CancelDNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error) {
	out := new(DNSChaosResponse)
	err := c.cc.Invoke(ctx, "/pb.DNS/CancelDNSChaos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSServer is the server API for DNS service.
type DNSServer interface {
	SetDNSChaos(context.Context, *SetDNSChaosRequest) (*DNSChaosResponse, error)
	CancelDNSChaos(context.Context, *CancelDNSChaosRequest) (*DNSChaosResponse, error)
}

// UnimplementedDNSServer can be embedded to have forward compatible implementations.
type UnimplementedDNSServer struct {
}

func (*UnimplementedDNSServer) SetDNSChaos(ctx context.Context, req *SetDNSChaosRequest) (*DNSChaosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDNSChaos not implemented")
}
func (*UnimplementedDNSServer) CancelDNSChaos(ctx context.Context, req *CancelDNSChaosRequest) (*DNSChaosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelDNSChaos not implemented")
}

func RegisterDNSServer(s *grpc.Server, srv DNSServer) {
	s.RegisterService(&_DNS_serviceDesc, srv)
}

func _DNS_SetDNSChaos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDNSChaosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServer).SetDNSChaos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DNS/SetDNSChaos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServer).SetDNSChaos(ctx, req.(*SetDNSChaosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNS_CancelDNSChaos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDNSChaosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSServer).CancelDNSChaos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DNS/CancelDNSChaos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSServer).CancelDNSChaos(ctx, req.(*CancelDNSChaosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DNS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DNS",
	HandlerType: (*DNSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDNSChaos",
			Handler:    _DNS_SetDNSChaos_Handler,
		},
		{
			MethodName: "CancelDNSChaos",
			Handler:    _DNS_CancelDNSChaos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns.proto",
}
